name: "Our Home Connected"
description: "Version control for your Home Assistant automations and scripts with GitHub integration"
version: "0.1.2"
slug: "ourhomeconnected"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "ghcr.io/danieldotnl/ourhomeconnected-{arch}"
startup: application
boot: auto
ingress: true
ingress_port: 8000
panel_icon: mdi:git
panel_title: "OHC"
map:
  - config:rw
environment:
  ENVIRONMENT: "prod"
  HA_SERVER: "http://supervisor/core"
  HA_DATA_FOLDER: "/data"