name: "Our Home Connected"
description: "Version control for your Home Assistant automations and scripts with GitHub integration"
version: "v0.1.8"
slug: "ourhomeconnected"
init: false
arch:
  - aarch64
  - amd64
image: "ghcr.io/danieldotnl/ourhomeconnected-addon-{arch}"
ports:
  8000/tcp: 8000
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)

ingress: true
ingress_port: 8000
panel_icon: mdi:git
panel_title: "OHC"
homeassistant_api: true
environment:
  ENVIRONMENT: "prod"