name: Build and publish add-on

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download OHC Backend
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-package.yml
          repo: danieldotnl/ohc-addon-backend
          name: ohc-backend-package
          path: backend-package

      # Create a temp directory for build context
      - name: Prepare build context
        run: |
          mkdir -p build-context
          cp -r ourhomeconnected/* build-context/
          mkdir -p build-context/backend-package
          cp backend-package/*.whl build-context/backend-package/
          ls -la build-context/
          ls -la build-context/backend-package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/ourhomeconnected
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: build-context
          platforms: linux/${{ matrix.arch }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/ourhomeconnected-${{ matrix.arch }}:${{ steps.meta.outputs.version }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base:latest

      - name: Update version in config.yaml
        if: startsWith(github.ref, 'refs/tags/v')
        uses: fjogeleit/yaml-update-action@v0.13.1
        with:
          valueFile: 'ourhomeconnected/config.yaml'
          propertyPath: 'version'
          value: ${{ github.ref_name }}
          commitChange: true
          updateFile: true
          message: 'Update version to ${{ github.ref_name }}'
          branch: ${{ github.ref_name }}